on: push
jobs:
  test-self-hosted:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run command
        run: |
          ls ${{github.workspace}}
